stages:
  - build

flutter_build_android:
  stage: build
  image: cirrusci/flutter
  before_script:
    - flutter clean
    - flutter pub get
  script:
    - flutter test
    - flutter analyze
    - flutter build apk
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-release.apk
  tags:
    - flutter-build

flutter_build_ios:
  stage: build
  before_script:
    - flutter clean
    - flutter pub get
  script:
    - flutter build ios
    - cd ios
    - xcodebuild clean archive -workspace Runner.xcworkspace -scheme Runner -archivePath RunnerArchive
    - xcodebuild -exportArchive -archivePath RunnerArchive.xcarchive -exportOptionsPlist ./Runner/ExportOptions.plist -exportPath ./build
  artifacts:
    paths:
      - ios/build/passenger.ipa
  tags:
    - flutter-build-ios
