// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSoV181Lm1dldN1U1YMhIuoiUIZ3Luijk',
    appId: '1:345550591839:android:2faf8f08ee0ad3ccdf48ea',
    messagingSenderId: '345550591839',
    projectId: 'fir-26d34',
    databaseURL: 'https://fir-26d34-default-rtdb.firebaseio.com',
    storageBucket: 'fir-26d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKfIzmZY7ywdYyXoV7opAMrz3FY14wmj0',
    appId: '1:345550591839:ios:b3e11a67d75b869adf48ea',
    messagingSenderId: '345550591839',
    projectId: 'fir-26d34',
    databaseURL: 'https://fir-26d34-default-rtdb.firebaseio.com',
    storageBucket: 'fir-26d34.appspot.com',
    iosClientId: '345550591839-8gekbpssija3ed26t6oiatgnimkef58j.apps.googleusercontent.com',
    iosBundleId: 'th.co.robinhood.consumerdev',
  );
}
